import type { GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { createPrismicClient } from "../prismic-config";
import { asText } from "@prismicio/helpers";

export async function getStaticProps({ previewData }: GetStaticPropsContext) {
  const client = createPrismicClient({ previewData });

  // const home = await client.getByUID("page", "home");

  return {
    props: {
      title: "Test",
    },
  };
}

const Index: NextPage = (props) => {
  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome</h1>
    </div>
  );
};

export default Index;
